#!/usr/bin/env python3
# tab-width:4

from __future__ import annotations

# Auto-generated by generate_color_palettes.py
# Names ending in '_r' are reversed variants.

COLOR_PALETTES = {
    "Perceptually Uniform": [
        "cividis",
        "plasma",
        "viridis",
    ],
    "Sequential": [
        "autumn",
        "cool",
        "turbo",
    ],
    "Diverging": [
        "RdYlBu",
    ],
    "Cyclic": [
        "hsv",
    ],
    "Miscellaneous": [
        "brg",
        "gist_ncar",
        "gist_rainbow",
        "jet",
        "nipy_spectral",
    ],
}
